# 將成績表的學號，自動換成班級座號

    由於學號是以全學年為單位分配，但製作成績單需要的是座號
    因此用一個全校名調來進行轉換

In [8]:
# 看看手上成績表的格式，原始資料是以 big5 編碼
df = pd.read_csv(basepath+'107-3.2-高二和資訊科技(1).csv', engine='python', encoding='big5')
df

,名次,account,姓名,真實姓名,備註,學校,答對,送出,時間,分數
0,1,610258@stu.nknush.kh.edu.tw,610258洪恩琪,610258洪恩琪,NaN,NaN,2,2,10117,100
1,2,610110@stu.nknush.kh.edu.tw,610110汪李芊,610110汪李芊,NaN,NaN,2,7,13257,100
2,3,610002@stu.nknush.kh.edu.tw,610002吳偌嫣,610002吳偌嫣,NaN,NaN,2,3,20203,100
3,4,610113@stu.nknush.kh.edu.tw,610113張宥棋,610113張宥棋,NaN,NaN,1,1,16,50
4,5,610147@stu.nknush.kh.edu.tw,610147林閔晴,610147林閔晴,NaN,NaN,1,2,22,50
5,6,610048@stu.nknush.kh.edu.tw,610048王彥傑,610048王彥傑,NaN,NaN,1,2,9087,50
6,7,610165@stu.nknush.kh.edu.tw,610165辛昀倢,610165辛昀倢,NaN,NaN,0,3,0,0
7,8,610183@stu.nknush.kh.edu.tw,610183林佳儀,610183林佳儀,NaN,NaN,0,0,0,0
8,8,610120@stu.nknush.kh.edu.tw,610120劉郁昕,610120劉郁昕,NaN,NaN,0,0,0,0
9,8,610119@stu.nknush.kh.edu.tw,610119齊品寧,610119齊品寧,NaN,NaN,0,0,0,0
10,8,610003@stu.nknush.kh.edu.tw,610003沈容君,610003沈容君,NaN,NaN,0,0,0,0
11,8,610150@stu.nknush.kh.edu.tw,610150張筑貽,610150張筑貽,NaN,NaN,0,0,0,0

### 我們發現，以上的乘積表沒有座號，難以排序，因此成績不容易登記。

### 我們希望資料當中的"學號"能夠自動對應出班級座號

In [6]:
# 首先，先看看全校名條的格式
import pandas as pd
df_source = pd.read_excel(basepath+'107-2--全校名條.xlsx', sheet_name='高中名條')

df_source.head(10)

      班級  座號        學號       姓名
0    高三仁   1  510218.0      何靜晏
1    高三仁   2       NaN      NaN
2    高三仁   3       NaN      NaN
3    高三仁   4  510004.0      易冠霈
4    高三仁   5  510257.0      邱瑞汶
5    高三仁   6       NaN      NaN
6    高三仁   7  510116.0      陳紀潔
7    高三仁   8  510117.0  麻亞。伊斯南冠
8    高三仁   9       NaN      NaN
9    高三仁  10  510187.0      葉宣妤
10   高三仁  11  510010.0      劉怡秀
11   高三仁  12  510045.0      潘品璇
12   高三仁  13  510046.0      蔡紀慈
13   高三仁  14  510155.0      尤柏智
14   高三仁  15  510119.0      方雍傑
15   高三仁  16  510229.0      王俊元
16   高三仁  17  510267.0      王耀民
17   高三仁  18  510268.0      何緯綸
18   高三仁  19       NaN      NaN
19   高三仁  20  510015.0      林昱君
20   高三仁  21  510198.0      林浡瀚
21   高三仁  22       NaN      NaN
22   高三仁  23  510234.0      林隆鴻
23   高三仁  24  510274.0       林顥
24   高三仁  25  510090.0      施寬含
25   高三仁  26  510275.0      翁竣彥
26   高三仁  27  510020.0      張世恩
27   高三仁  28       NaN      NaN
28   高三仁  29  510169.0      許廷郡
29   高三仁  30  510205.0      許耿山
..   ...  ..       ...      ...
865  高一和   8  710267.0      陳可薰
866  高一和   9  710268.0      陳妍禎
867  高一和  10  710269.0      陳怡婷
868  高一和  11  710270.0      劉芮安
869  高一和  12  710271.0      劉書華
870  高一和  13  710272.0      蔡芃芑
871  高一和  14  710273.0      王宇晢
872  高一和  15  710274.0      王品文
873  高一和  16  710275.0      王柏登
874  高一和  17  710276.0      王鐏鋐
875  高一和  18  710277.0      李運達
876  高一和  19  710278.0      李聰明
877  高一和  20  710279.0      杜郁友
878  高一和  21  710280.0      柯竣哲
879  高一和  22  710281.0      符傳祥
880  高一和  23  710282.0      陳友柏
881  高一和  24  710283.0       陳昕
882  高一和  25  710284.0      陳冠羽
883  高一和  26  710285.0      陳冠穎
884  高一和  27  710286.0      陳登相
885  高一和  28  710287.0      曾世融
886  高一和  29  710288.0      黃俊瑋
887  高一和  30  710289.0      黃楨翔
888  高一和  31  710290.0      葉昀鑫
889  高一和  32  710291.0      鄒兆中
890  高一和  33  710292.0      潘界谷
891  高一和  34  710293.0      蔡孟原
892  高一和  35  710294.0      鄭翔宇
893  高一和  36  710295.0      賴以恩
894  高一和  37  710296.0      鍾騏駿

[895 rows x 4 columns]

In [5]:
import pandas as pd

basepath = '.\\datas\\'
csvfiles = [
'107-3.2-高二和資訊科技(1).csv',
'107-3.2-高二和資訊科技(2).csv',
'107-3.2-高二和資訊科技(3).csv',
'107-3.2-高二和資訊科技(4).csv'
]

df_source = pd.read_excel(basepath+'107-2--全校名條.xlsx', sheet_name='高中名條')

for csvfile in csvfiles:
    # 先用 big5 嘗試開啟，若發生例外，再改用 UTF-8 開啟，這樣就可以將兩種編碼的檔案都順利打開
    try:
        df_scoreboard = pd.read_csv(basepath + csvfile, engine='python', encoding='big5')
    except Exception as e:
        df_scoreboard = pd.read_csv(basepath + csvfile, engine='python', encoding='utf-8')
    df_scoreboard['班級座號'] = pd.Series()
    for index, row in df_scoreboard.iterrows():
        try:
            studentid = row.account.split('@')[0]
            loc = df_source.loc[df_source['學號'] == int(studentid)]
            df_scoreboard['班級座號'][index] = str(loc['班級'].values[0]) + str(f'{loc["座號"].values[0]:02d}' )
        except Exception as e:
            # 遇到無法對應的資料，就直接跳到下一個。
            print(e)
            continue


    df_scoreboard.to_csv(basepath+'new_'+csvfile,index=False,sep=',',encoding='utf-8-sig')
    print(df_scoreboard)

C:\Users\jiangsir\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\jiangsir\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

    名次                      account         姓名       真實姓名  備註  學校  答對  送出  \
0    1  610258@stu.nknush.kh.edu.tw  610258洪恩琪  610258洪恩琪 NaN NaN   2   2
1    2  610110@stu.nknush.kh.edu.tw  610110汪李芊  610110汪李芊 NaN NaN   2   7
2    3  610002@stu.nknush.kh.edu.tw  610002吳偌嫣  610002吳偌嫣 NaN NaN   2   3
3    4  610113@stu.nknush.kh.edu.tw  610113張宥棋  610113張宥棋 NaN NaN   1   1
4    5  610147@stu.nknush.kh.edu.tw  610147林閔晴  610147林閔晴 NaN NaN   1   2
5    6  610048@stu.nknush.kh.edu.tw  610048王彥傑  610048王彥傑 NaN NaN   1   2
6    7  610165@stu.nknush.kh.edu.tw  610165辛昀倢  610165辛昀倢 NaN NaN   0   3
7    8  610183@stu.nknush.kh.edu.tw  610183林佳儀  610183林佳儀 NaN NaN   0   0
8    8  610120@stu.nknush.kh.edu.tw  610120劉郁昕  610120劉郁昕 NaN NaN   0   0
9    8  610119@stu.nknush.kh.edu.tw  610119齊品寧  610119齊品寧 NaN NaN   0   0
10   8  610003@stu.nknush.kh.edu.tw  610003沈容君  610003沈容君 NaN NaN   0   0
11   8  610150@stu.nknush.kh.edu.tw  610150張筑貽  610150張筑貽 NaN NaN   0   0

       時間   分數   班級座號
0   10117  100  高二和06
1   13257  100  高二和02
2   20203  100  高二和01
3      16   50  高二和07
4      22   50  高二和05
5    9087   50  高二和18
6       0    0  高二和20
7       0    0  高二和04
8       0    0  高二和13
9       0    0  高二和12
10      0    0  高二和03
11      0    0  高二和08
invalid literal for int() with base 10: 'nate5612369'
    名次                      account          姓名        真實姓名  \
0    1  610113@stu.nknush.kh.edu.tw   610113張宥棋   610113張宥棋
1    2  610158@stu.nknush.kh.edu.tw   610158丁俊宇   610158丁俊宇
2    3  610150@stu.nknush.kh.edu.tw   610150張筑貽   610150張筑貽
3    4  610212@stu.nknush.kh.edu.tw   610212賴奕安   610212賴奕安
4    5  610045@stu.nknush.kh.edu.tw   610045鄭巧芸   610045鄭巧芸
5    6        nate5612369@gmail.com  Nate Cheng  Nate Cheng
6    7  610119@stu.nknush.kh.edu.tw   610119齊品寧   610119齊品寧
7    7  610088@stu.nknush.kh.edu.tw   610088王睿彬   610088王睿彬
8    9  610166@stu.nknush.kh.edu.tw   610166林子甯   610166林子甯
9    9  610288@stu.nknush.kh.edu.tw   610288溫宥鈞   610288溫宥鈞
10  11  610251@stu.nknush.kh.edu.tw   610251劉培遠   610251劉培遠
11  11  610191@stu.nknush.kh.edu.tw   610191董玟妗   610191董玟妗
12  13  610064@stu.nknush.kh.edu.tw   610064陳柏均   610064陳柏均
13  14  610193@stu.nknush.kh.edu.tw   610193鄭婕妤   610193鄭婕妤
14  15  610110@stu.nknush.kh.edu.tw   610110汪李芊   610110汪李芊
15  16  610002@stu.nknush.kh.edu.tw   610002吳偌嫣   610002吳偌嫣
16  17  610186@stu.nknush.kh.edu.tw   610186陳暄宜   610186陳暄宜
17  18  610048@stu.nknush.kh.edu.tw   610048王彥傑   610048王彥傑
18  19  610003@stu.nknush.kh.edu.tw   610003沈容君   610003沈容君
19  20  610183@stu.nknush.kh.edu.tw   610183林佳儀   610183林佳儀
20  21  610242@stu.nknush.kh.edu.tw   610242洪上恩   610242洪上恩
21  22  610122@stu.nknush.kh.edu.tw   610122顏邵萱   610122顏邵萱
22  23  610205@stu.nknush.kh.edu.tw   610205曾睿誌   610205曾睿誌
23  24  610147@stu.nknush.kh.edu.tw   610147林閔晴   610147林閔晴
24  25  610120@stu.nknush.kh.edu.tw   610120劉郁昕   610120劉郁昕
25  26  610258@stu.nknush.kh.edu.tw   610258洪恩琪   610258洪恩琪
26  27  610171@stu.nknush.kh.edu.tw   610171陳軍瑋   610171陳軍瑋
27  28  610165@stu.nknush.kh.edu.tw   610165辛昀倢   610165辛昀倢
28  29  610247@stu.nknush.kh.edu.tw   610247黃豐杰   610247黃豐杰
29  30  610083@stu.nknush.kh.edu.tw   610083趙珍甄   610083趙珍甄

                                               備註  學校  答對  送出     時間   分數  \
0                                             NaN NaN   3   6  40341  300
1                                             NaN NaN   1   8     31  140
2                                             NaN NaN   1   1     29  100
3                                             NaN NaN   1   1     30  100
4                                             NaN NaN   1   4     30  100
5   https://plus.google.com/106414286606944402146 NaN   1   1     31  100
6                                             NaN NaN   1   1     32  100
7                                             NaN NaN   1   1     32  100
8                                             NaN NaN   1   1     34  100
9                                             NaN NaN   1   1     34  100
10                                            NaN NaN   1   1     35  100
11                                            NaN NaN   1   1     35  100
12                                            NaN NaN   1   3     35  100
13                                            NaN NaN   1   1     36  100
14                                            NaN NaN   1   2     46  100
15                                            NaN NaN   1   5     49  100
16                                            NaN NaN   1   2     55  100
17                                            NaN NaN   1   2     58  100
18                                            NaN NaN   1   3     71  100
19                                            NaN NaN   1   3     72  100
20                                            NaN NaN   1   4     94  100
21                                            NaN NaN   1   5    113  100
22                                            NaN NaN   1   5    118  100
23                                            NaN NaN   1   7    150  100
24                                            NaN NaN   1   8    155  100
25                                            NaN NaN   1  10    210  100
26                                            NaN NaN   1   1  10107  100
27                                            NaN NaN   0  11      0   10
28                                            NaN NaN   0   1      0    0
29                                            NaN NaN   0   0      0    0

     班級座號
0   高二和07
1   高二和17
2   高二和08
3   高二和30
4   高二和14
5     NaN
6   高二和12
7   高二和19
8   高二和21
9   高二和26
10  高二和27
11  高二和10
12  高二和23
13  高二和15
14  高二和02
15  高二和01
16  高二和09
17  高二和18
18  高二和03
19  高二和04
20  高二和22
21  高二和16
22  高二和24
23  高二和05
24  高二和13
25  高二和06
26  高二和31
27  高二和20
28  高二和25
29  高二和11
invalid literal for int() with base 10: 'nate5612369'
    名次                      account          姓名        真實姓名  \
0    1  610088@stu.nknush.kh.edu.tw   610088王睿彬   610088王睿彬
1    2  610158@stu.nknush.kh.edu.tw   610158丁俊宇   610158丁俊宇
2    3  610205@stu.nknush.kh.edu.tw   610205曾睿誌   610205曾睿誌
3    4  610183@stu.nknush.kh.edu.tw   610183林佳儀   610183林佳儀
4    5  610002@stu.nknush.kh.edu.tw   610002吳偌嫣   610002吳偌嫣
5    6  610122@stu.nknush.kh.edu.tw   610122顏邵萱   610122顏邵萱
6    7  610110@stu.nknush.kh.edu.tw   610110汪李芊   610110汪李芊
7    8  610120@stu.nknush.kh.edu.tw   610120劉郁昕   610120劉郁昕
8    9  610247@stu.nknush.kh.edu.tw   610247黃豐杰   610247黃豐杰
9   10  610212@stu.nknush.kh.edu.tw   610212賴奕安   610212賴奕安
10  11  610083@stu.nknush.kh.edu.tw   610083趙珍甄   610083趙珍甄
11  12  610147@stu.nknush.kh.edu.tw   610147林閔晴   610147林閔晴
12  13  610258@stu.nknush.kh.edu.tw   610258洪恩琪   610258洪恩琪
13  14  610064@stu.nknush.kh.edu.tw   610064陳柏均   610064陳柏均
14  15  610031@stu.nknush.kh.edu.tw   610031鄭宇同   610031鄭宇同
15  16  610113@stu.nknush.kh.edu.tw   610113張宥棋   610113張宥棋
16  17  610119@stu.nknush.kh.edu.tw   610119齊品寧   610119齊品寧
17  18  610193@stu.nknush.kh.edu.tw   610193鄭婕妤   610193鄭婕妤
18  19  610003@stu.nknush.kh.edu.tw   610003沈容君   610003沈容君
19  20  610045@stu.nknush.kh.edu.tw   610045鄭巧芸   610045鄭巧芸
20  21  610191@stu.nknush.kh.edu.tw   610191董玟妗   610191董玟妗
21  22  610242@stu.nknush.kh.edu.tw   610242洪上恩   610242洪上恩
22  23  610166@stu.nknush.kh.edu.tw   610166林子甯   610166林子甯
23  24  610251@stu.nknush.kh.edu.tw   610251劉培遠   610251劉培遠
24  25        nate5612369@gmail.com  Nate Cheng  Nate Cheng
25  26  610288@stu.nknush.kh.edu.tw   610288溫宥鈞   610288溫宥鈞
26  27  610186@stu.nknush.kh.edu.tw   610186陳暄宜   610186陳暄宜
27  28  610171@stu.nknush.kh.edu.tw   610171陳軍瑋   610171陳軍瑋
28  29  610048@stu.nknush.kh.edu.tw   610048王彥傑   610048王彥傑
29  30  610150@stu.nknush.kh.edu.tw   610150張筑貽   610150張筑貽
30  31  610165@stu.nknush.kh.edu.tw   610165辛昀倢   610165辛昀倢

                                               備註  學校  答對  送出      時間   分數  \
0                                             NaN NaN   8  14  391266  800
1                                             NaN NaN   8   8  409602  800
2                                             NaN NaN   7  27  471587  700
3                                             NaN NaN   6  37  331550  690
4                                             NaN NaN   6  24  394808  690
5                                             NaN NaN   6   9  297297  600
6                                             NaN NaN   5  35  138637  590
7                                             NaN NaN   5  18  214153  590
8                                             NaN NaN   5  16  270582  530
9                                             NaN NaN   5  12  141435  500
10                                            NaN NaN   5  14  213950  500
11                                            NaN NaN   4  25  131426  490
12                                            NaN NaN   4  40  131558  490
13                                            NaN NaN   4  12  131270  430
14                                            NaN NaN   4  13   60778  400
15                                            NaN NaN   4  15  111087  400
16                                            NaN NaN   4   7  131221  400
17                                            NaN NaN   4   6  131234  400
18                                            NaN NaN   4  10  131318  400
19                                            NaN NaN   4  16  131400  400
20                                            NaN NaN   4   4  171519  400
21                                            NaN NaN   3  17   90916  390
22                                            NaN NaN   3  10  111069  390
23                                            NaN NaN   3  20   50757  330
24  https://plus.google.com/106414286606944402146 NaN   3   7   30348  300
25                                            NaN NaN   3   6   50575  300
26                                            NaN NaN   3  10   90953  300
27                                            NaN NaN   3   3  173447  300
28                                            NaN NaN   2   3   80726  200
29                                            NaN NaN   2   3  161391  200
30                                            NaN NaN   1  10   30286  100

     班級座號
0   高二和19
1   高二和17
2   高二和24
3   高二和04
4   高二和01
5   高二和16
6   高二和02
7   高二和13
8   高二和25
9   高二和30
10  高二和11
11  高二和05
12  高二和06
13  高二和23
14  高二和28
15  高二和07
16  高二和12
17  高二和15
18  高二和03
19  高二和14
20  高二和10
21  高二和22
22  高二和21
23  高二和27
24    NaN
25  高二和26
26  高二和09
27  高二和31
28  高二和18
29  高二和08
30  高二和20

    名次                      account         姓名       真實姓名  備註  學校  答對  送出  \
0    1  610258@stu.nknush.kh.edu.tw  610258洪恩琪  610258洪恩琪 NaN NaN   3  17
1    2  610147@stu.nknush.kh.edu.tw  610147林閔晴  610147林閔晴 NaN NaN   3  10
2    3  610113@stu.nknush.kh.edu.tw  610113張宥棋  610113張宥棋 NaN NaN   3   7
3    4  610150@stu.nknush.kh.edu.tw  610150張筑貽  610150張筑貽 NaN NaN   3  11
4    5  610002@stu.nknush.kh.edu.tw  610002吳偌嫣  610002吳偌嫣 NaN NaN   2   8
5    6  610122@stu.nknush.kh.edu.tw  610122顏邵萱  610122顏邵萱 NaN NaN   2   2
6    7  610120@stu.nknush.kh.edu.tw  610120劉郁昕  610120劉郁昕 NaN NaN   2  10
7    8  610183@stu.nknush.kh.edu.tw  610183林佳儀  610183林佳儀 NaN NaN   2  15
8    9  610171@stu.nknush.kh.edu.tw  610171陳軍瑋  610171陳軍瑋 NaN NaN   2   2
9   10  610110@stu.nknush.kh.edu.tw  610110汪李芊  610110汪李芊 NaN NaN   2   7
10  11  610048@stu.nknush.kh.edu.tw  610048王彥傑  610048王彥傑 NaN NaN   2   2
11  12  610247@stu.nknush.kh.edu.tw  610247黃豐杰  610247黃豐杰 NaN NaN   1   8
12  13  610158@stu.nknush.kh.edu.tw  610158丁俊宇  610158丁俊宇 NaN NaN   1   1
13  14  610193@stu.nknush.kh.edu.tw  610193鄭婕妤  610193鄭婕妤 NaN NaN   1   1
14  15  610212@stu.nknush.kh.edu.tw  610212賴奕安  610212賴奕安 NaN NaN   1   2
15  16  610119@stu.nknush.kh.edu.tw  610119齊品寧  610119齊品寧 NaN NaN   1   2
16  16  610003@stu.nknush.kh.edu.tw  610003沈容君  610003沈容君 NaN NaN   1   2
17  18  610083@stu.nknush.kh.edu.tw  610083趙珍甄  610083趙珍甄 NaN NaN   1   3
18  19  610064@stu.nknush.kh.edu.tw  610064陳柏均  610064陳柏均 NaN NaN   1   4
19  20  610045@stu.nknush.kh.edu.tw  610045鄭巧芸  610045鄭巧芸 NaN NaN   1   1
20  21  610166@stu.nknush.kh.edu.tw  610166林子甯  610166林子甯 NaN NaN   1   1
21  22  610186@stu.nknush.kh.edu.tw  610186陳暄宜  610186陳暄宜 NaN NaN   1   2
22  23  610191@stu.nknush.kh.edu.tw  610191董玟妗  610191董玟妗 NaN NaN   1   1
23  24  610242@stu.nknush.kh.edu.tw  610242洪上恩  610242洪上恩 NaN NaN   1   1
24  25  610288@stu.nknush.kh.edu.tw  610288溫宥鈞  610288溫宥鈞 NaN NaN   0   1
25  26  610251@stu.nknush.kh.edu.tw  610251劉培遠  610251劉培遠 NaN NaN   0   4
26  27  610205@stu.nknush.kh.edu.tw  610205曾睿誌  610205曾睿誌 NaN NaN   0   0
27  27  610165@stu.nknush.kh.edu.tw  610165辛昀倢  610165辛昀倢 NaN NaN   0   0
28  27  610088@stu.nknush.kh.edu.tw  610088王睿彬  610088王睿彬 NaN NaN   0   0
29  27  610031@stu.nknush.kh.edu.tw  610031鄭宇同  610031鄭宇同 NaN NaN   0   0

       時間   分數   班級座號
0   30669  300  高二和06
1   50669  300  高二和05
2   70734  300  高二和07
3   72812  300  高二和08
4   10215  200  高二和01
5   20258  200  高二和16
6   30407  200  高二和13
7   39892  200  高二和04
8   40355  200  高二和31
9   59955  200  高二和02
10  75972  200  高二和18
11     73  180  高二和25
12     42  100  高二和17
13     46  100  高二和15
14     46  100  高二和30
15     48  100  高二和12
16     48  100  高二和03
17     51  100  高二和11
18     52  100  高二和23
19  10082  100  高二和14
20  10125  100  高二和21
21  10128  100  高二和09
22  10129  100  高二和10
23  20161  100  高二和22
24      0    0  高二和26
25      0    0  高二和27
26      0    0  高二和24
27      0    0  高二和20
28      0    0  高二和19
29      0    0  高二和28